/********************************************************************
* ThrmRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ThrmRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableThrmRootDict();
extern void G__cpp_setup_inheritanceThrmRootDict();
extern void G__cpp_setup_typetableThrmRootDict();
extern void G__cpp_setup_memvarThrmRootDict();
extern void G__cpp_setup_globalThrmRootDict();
extern void G__cpp_setup_memfuncThrmRootDict();
extern void G__cpp_setup_funcThrmRootDict();
extern void G__set_cpp_environmentThrmRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ThrmMemStat.h"
#include "ThrmFourVector.h"
#include "ThrmJetReco.h"
#include "ThrmRecPythia.h"
#include "ThrmJet.h"
#include "ThrmPythiaTest.h"
#include "ThrmPythiaEmb.h"
#include "ThrmEvent.h"
#include "ThrmSimPythiaJet.h"
#include "ThrmEmbedding.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ThrmRootDictLN_TClass;
extern G__linked_taginfo G__ThrmRootDictLN_TBuffer;
extern G__linked_taginfo G__ThrmRootDictLN_TMemberInspector;
extern G__linked_taginfo G__ThrmRootDictLN_TObject;
extern G__linked_taginfo G__ThrmRootDictLN_TNamed;
extern G__linked_taginfo G__ThrmRootDictLN_TString;
extern G__linked_taginfo G__ThrmRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ThrmRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ThrmRootDictLN_TList;
extern G__linked_taginfo G__ThrmRootDictLN_TClonesArray;
extern G__linked_taginfo G__ThrmRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ThrmRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmMemStat;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ThrmRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ThrmRootDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ThrmRootDictLN_TLorentzVector;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmFourVector;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmJetReco;
extern G__linked_taginfo G__ThrmRootDictLN_TF1;
extern G__linked_taginfo G__ThrmRootDictLN_TH1D;
extern G__linked_taginfo G__ThrmRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ThrmRootDictLN_TPythia6;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmJet;
extern G__linked_taginfo G__ThrmRootDictLN_TH2D;
extern G__linked_taginfo G__ThrmRootDictLN_TFile;
extern G__linked_taginfo G__ThrmRootDictLN_TTree;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmPythiaTest;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmPythiaEmb;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmEvent;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmSimPythiaJet;
extern G__linked_taginfo G__ThrmRootDictLN_ThrmEmbedding;

/* STUB derived class for protected member access */
